[[Unishox]]
arch = "aarch64"
git-tree-sha1 = "ea5baa6b7be25736d93f224ed4143fd9843674c6"
os = "macos"

    [[Unishox.download]]
    sha256 = "64ae980fd944d65f785a0fb124cded8f44bd84bfdd2db39f146337157a34bd46"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.aarch64-apple-darwin.tar.gz"
[[Unishox]]
arch = "aarch64"
git-tree-sha1 = "80fef1e821f96e76238414f2101414e2ab2201b4"
libc = "glibc"
os = "linux"

    [[Unishox.download]]
    sha256 = "94f0be0854c8207575f45f9f4453d775120448464fdd18f79157f86888c2a6a8"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.aarch64-linux-gnu.tar.gz"
[[Unishox]]
arch = "aarch64"
git-tree-sha1 = "d87fe8f334750cf19c0e7b5c1c8d352073464b42"
libc = "musl"
os = "linux"

    [[Unishox.download]]
    sha256 = "010a17ffcbbb63f8fa378e16a658b7f2ec999efaef9bc555de07017fcea36c84"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.aarch64-linux-musl.tar.gz"
[[Unishox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4ca5afe0e57dea81ebc55784121e1c2d7be3e3e9"
libc = "glibc"
os = "linux"

    [[Unishox.download]]
    sha256 = "ee546a782e790bc242dde985cb0948db8ca2270fbed3ae84a2302992ef45c49b"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.armv6l-linux-gnueabihf.tar.gz"
[[Unishox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6ed123825b24d9bb26ad056d890331475b8a1538"
libc = "musl"
os = "linux"

    [[Unishox.download]]
    sha256 = "92b696df5eb8dab803ab729f7eea5638813c2a8b8c49b7d61eae045ab4c5926b"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.armv6l-linux-musleabihf.tar.gz"
[[Unishox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f7432b812adeb7c3b77c2bfcef435dce35407197"
libc = "glibc"
os = "linux"

    [[Unishox.download]]
    sha256 = "018d71a843f226e1b488b0f3222e9e678704ddf4dca324956b87ced6e65232f1"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.armv7l-linux-gnueabihf.tar.gz"
[[Unishox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f7e11de9189cc6ffa435375dc734aabf6d8c21f6"
libc = "musl"
os = "linux"

    [[Unishox.download]]
    sha256 = "62529461544e95a11873a76e803ec93ba4511e076fad42187d4e5549c33c32ed"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.armv7l-linux-musleabihf.tar.gz"
[[Unishox]]
arch = "i686"
git-tree-sha1 = "26b72910b76d4897888257a8d74543a4c4015d4c"
libc = "glibc"
os = "linux"

    [[Unishox.download]]
    sha256 = "933336fb519a6b14abdd9ae402967da38462944acfc160befef2348ebdf0b493"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.i686-linux-gnu.tar.gz"
[[Unishox]]
arch = "i686"
git-tree-sha1 = "418aea1c9e275af94f61d98c1f5554edf6f2d658"
libc = "musl"
os = "linux"

    [[Unishox.download]]
    sha256 = "e5480daaf8c4f7c916e203a4aeda50220cfab71ee3e6dd74a942c1ce912c7dab"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.i686-linux-musl.tar.gz"
[[Unishox]]
arch = "i686"
git-tree-sha1 = "db810a4a95fbfc0921133a531c2ba478cfee6ab2"
os = "windows"

    [[Unishox.download]]
    sha256 = "c0a7f237b1811932a5850a6b165fd60fefcae9a6a1e562a087c3bffa53b54a4d"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.i686-w64-mingw32.tar.gz"
[[Unishox]]
arch = "powerpc64le"
git-tree-sha1 = "0bbf5ba65feb0d072eeaf0fe5ae3e95373b8b24a"
libc = "glibc"
os = "linux"

    [[Unishox.download]]
    sha256 = "4695cf4570f20613ddd27f337bbf14371f4ad6a65f5e884fdf377a77357d376b"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.powerpc64le-linux-gnu.tar.gz"
[[Unishox]]
arch = "x86_64"
git-tree-sha1 = "4fc6ae1a1873345b58b88f59f9c607088a7de22b"
os = "macos"

    [[Unishox.download]]
    sha256 = "69a30258527e1daaa5e4c60de58204e55d8d9c848a93c43720b2e787c370cef8"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.x86_64-apple-darwin.tar.gz"
[[Unishox]]
arch = "x86_64"
git-tree-sha1 = "1f8e49b164239c8d384706d583b3631cb6015cad"
libc = "glibc"
os = "linux"

    [[Unishox.download]]
    sha256 = "14e85217feb6537ab8c0ae00ae969f90576e5d58967c0fa6b28ebac4430be034"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.x86_64-linux-gnu.tar.gz"
[[Unishox]]
arch = "x86_64"
git-tree-sha1 = "8e5ec58a8d24deb16099ab751f96f68e64410d47"
libc = "musl"
os = "linux"

    [[Unishox.download]]
    sha256 = "b414d95768ec8605cabca8a7900e63c501c1b96de935bdfb521f02e6f027eb39"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.x86_64-linux-musl.tar.gz"
[[Unishox]]
arch = "x86_64"
git-tree-sha1 = "1e808b13d50edcff5ce2873fa379254270e0738f"
os = "freebsd"

    [[Unishox.download]]
    sha256 = "0f1d671333de731f04191a8dcf9d97a0d829fe3d88e072c49d9ef119cc931aed"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.x86_64-unknown-freebsd.tar.gz"
[[Unishox]]
arch = "x86_64"
git-tree-sha1 = "c59b9d9be2a3fc7e56dd62312d4fede540981d17"
os = "windows"

    [[Unishox.download]]
    sha256 = "2f8f8244f2472beaee25b8be34bc43fe8cdc21c676a5226cf60c44b2845dc9cb"
    url = "https://github.com/JuliaBinaryWrappers/Unishox_jll.jl/releases/download/Unishox-v1.0.2+0/Unishox.v1.0.2.x86_64-w64-mingw32.tar.gz"
